### ISSUE TITLE
Slecting a child does not select the parent

### ISSUE THREAD

**Issue by leonardoayres** [GiuseppeSperanza/multiselect_nested#1]
Hello, how are you?

I'm trying to use your component and I've faced an issue related to selection.

When I select a parent, all the children are selected. Nice, expected behavior; but when I select just the child, I suppose that the parent should be selected (mainly to notify the user that exist a selected option when the children list is collapsed), but it is not happening.

Can you consider to do this upgrade or even set this as a configurable option?

All the best.

**Comment by GiuseppeSperanza** [comment]
Hi, thank you for your feedback. I plan to work on a similar feature where if you select a child i'll show a flag near his parent, any case you will not see the parent in the final model.

**Comment by GiuseppeSperanza** [comment]
Check it out the new version. I added the **checkParentWhenChildIsSelected** prop
